package week06Final;

public class Card { // So this is a class we can call in other parts of our package.
	String name; // We establish the variables used by this class. These are our inputs.
	String suit;
	int value;
	
	Card(String name, String suit, int value) { // This defines the structure of how we use these variables.
		this.name = name; // This is so the program knows we're using local instances of these variables. 
		this.suit = suit;
		this.value = value;
	}

	public String getName() { // These are our getters and setters. They are automatically generated by Eclipse.
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSuit() {
		return suit;
	}

	public void setSuit(String suit) {
		this.suit = suit;
	}

	public int getValue() {
		return value;
	}

	public void setValue(int value) {
		this.value = value;
	}
	
	public void describe() { // This is a sub command we can attach to this class to perform a specific action. 
		System.out.println(this.name + " of " + this.suit + " (" + this.value + ")"); // And in this case, it prints out the card we've given it. 
	}
}
